#!/bin/bash
set -e

#Create 'wisefood' database and wisefood user
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE ROLE "$WISEFOOD_USER" NOSUPERUSER CREATEDB CREATEROLE LOGIN PASSWORD '$WISEFOOD_PASSWORD';
    CREATE DATABASE "$WISEFOOD_DB" OWNER "$WISEFOOD_USER" ENCODING 'utf-8';
    CREATE SCHEMA "$WISEFOOD_SCHEMA";
EOSQL

# Create Keycloak user
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE ROLE "$KEYCLOAK_USER" NOSUPERUSER CREATEDB CREATEROLE LOGIN PASSWORD '$KEYCLOAK_PASSWORD';
EOSQL

# Connect to the newly created database and create the schema
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" "$KEYCLOAK_DB" <<-EOSQL
    CREATE SCHEMA "$KEYCLOAK_SCHEMA";
EOSQL

# Assign privileges on the keycloak schema to the Keycloak user
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" "$KEYCLOAK_DB" <<-EOSQL
    GRANT ALL PRIVILEGES ON SCHEMA "$KEYCLOAK_SCHEMA" TO "$KEYCLOAK_USER";
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "$KEYCLOAK_SCHEMA" TO "$KEYCLOAK_USER";
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "$KEYCLOAK_SCHEMA" TO "$KEYCLOAK_USER";
EOSQL